POST http://localhost:3000/clients
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:3000/accounts
Content-Type: application/json

{
    "client_id": "f6ce068e-4d0d-4a9b-b253-a0a035db76eb"
}

### 

POST http://localhost:3000/transactions
Content-Type: application/json

{
    "account_id_from": "d683df34-178d-4d87-98b7-bd7c52a9ab02",
    "account_id_to": "da747d48-d0e5-435b-bf4c-4422dab475b0",
    "amount": 50
}