POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "client_id": "5404e754-c6ca-4457-a43d-a3bb95e9aaff"
}

### 

POST http://localhost:8080/transactions
Content-Type: application/json

{
    "account_id_from": "7ff8c654-898e-4c44-9c5d-ccda5da8cc5a",
    "account_id_to": "c840a1d5-591f-4dd9-bbaf-480a1d414cfa",
    "amount": 10
}